services:
  clab:
    container_name: clab-k8s
    tty: true
    restart: always
    image: ghcr.io/srl-labs/clab
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - clab-volume:/var/run/docker.sock:/var/run/docker.sock
      - clab-volume:/var/run/netns
      - clab-volume:/etc/hosts
      - clab-volume:/var/lib/docker/containers

volumes:
  clab-volume:
    name: clab-volume